import type { Kanji } from "./kanji-types";

/** 小学2年生で習う漢字 160字 */
export const KANJI_LIST: Kanji[] = [
  { char: "引", on: ["イン"], kun: ["ひ"], meaning: "ひっぱる", examples: [{ word: "引力", reading: "いんりょく" }, { word: "引く", reading: "ひく" }], strokes: 4 },
  { char: "羽", on: ["ウ"], kun: ["は", "はね"], meaning: "とりのはね", examples: [{ word: "羽根", reading: "はね" }, { word: "白い羽", reading: "しろいはね" }], strokes: 6 },
  { char: "雲", on: ["ウン"], kun: ["くも"], meaning: "そらのくも", examples: [{ word: "雲海", reading: "うんかい" }, { word: "白雲", reading: "しらくも" }], strokes: 12 },
  { char: "園", on: ["エン"], kun: ["その"], meaning: "おにわ・こうえん", examples: [{ word: "公園", reading: "こうえん" }, { word: "園長", reading: "えんちょう" }], strokes: 13 },
  { char: "遠", on: ["エン"], kun: ["とお"], meaning: "とおい", examples: [{ word: "遠足", reading: "えんそく" }, { word: "遠い", reading: "とおい" }], strokes: 13 },
  { char: "何", on: ["カ"], kun: ["なに", "なん"], meaning: "なに・なん", examples: [{ word: "何回", reading: "なんかい" }, { word: "何時", reading: "なんじ" }], strokes: 7 },
  { char: "科", on: ["カ"], kun: [], meaning: "かもく", examples: [{ word: "科学", reading: "かがく" }, { word: "教科", reading: "きょうか" }], strokes: 9 },
  { char: "夏", on: ["カ", "ゲ"], kun: ["なつ"], meaning: "あつい きせつ", examples: [{ word: "夏休み", reading: "なつやすみ" }, { word: "立夏", reading: "りっか" }], strokes: 10 },
  { char: "家", on: ["カ", "ケ"], kun: ["いえ", "や"], meaning: "おうち", examples: [{ word: "家族", reading: "かぞく" }, { word: "家", reading: "いえ" }], strokes: 10 },
  { char: "歌", on: ["カ"], kun: ["うた"], meaning: "うた・うたう", examples: [{ word: "歌手", reading: "かしゅ" }, { word: "校歌", reading: "こうか" }], strokes: 14 },
  { char: "画", on: ["ガ", "カク"], kun: [], meaning: "え・かく", examples: [{ word: "図画", reading: "ずが" }, { word: "計画", reading: "けいかく" }], strokes: 8 },
  { char: "回", on: ["カイ", "エ"], kun: ["まわ"], meaning: "まわる・かい", examples: [{ word: "一回", reading: "いっかい" }, { word: "回る", reading: "まわる" }], strokes: 6 },
  { char: "会", on: ["カイ", "エ"], kun: ["あ"], meaning: "あう・あつまり", examples: [{ word: "会社", reading: "かいしゃ" }, { word: "会う", reading: "あう" }], strokes: 6 },
  { char: "海", on: ["カイ"], kun: ["うみ"], meaning: "うみ", examples: [{ word: "海水", reading: "かいすい" }, { word: "海", reading: "うみ" }], strokes: 9 },
  { char: "絵", on: ["エ", "カイ"], kun: [], meaning: "え", examples: [{ word: "絵本", reading: "えほん" }, { word: "絵画", reading: "かいが" }], strokes: 12 },
  { char: "外", on: ["ガイ", "ゲ"], kun: ["そと", "ほか"], meaning: "そと", examples: [{ word: "外国", reading: "がいこく" }, { word: "外", reading: "そと" }], strokes: 5 },
  { char: "角", on: ["カク"], kun: ["かど", "つの"], meaning: "かど・つの", examples: [{ word: "三角", reading: "さんかく" }, { word: "角", reading: "つの" }], strokes: 7 },
  { char: "楽", on: ["ガク", "ラク"], kun: ["たの"], meaning: "たのしい・おんがく", examples: [{ word: "音楽", reading: "おんがく" }, { word: "楽しい", reading: "たのしい" }], strokes: 13 },
  { char: "活", on: ["カツ"], kun: [], meaning: "いきいきする", examples: [{ word: "生活", reading: "せいかつ" }, { word: "活動", reading: "かつどう" }], strokes: 9 },
  { char: "間", on: ["カン", "ケン"], kun: ["あいだ", "ま"], meaning: "あいだ", examples: [{ word: "時間", reading: "じかん" }, { word: "間", reading: "あいだ" }], strokes: 12 },
  { char: "丸", on: ["ガン"], kun: ["まる"], meaning: "まるい", examples: [{ word: "丸太", reading: "まるた" }, { word: "丸い", reading: "まるい" }], strokes: 3 },
  { char: "岩", on: ["ガン"], kun: ["いわ"], meaning: "おおきな いし", examples: [{ word: "岩石", reading: "がんせき" }, { word: "岩", reading: "いわ" }], strokes: 8 },
  { char: "顔", on: ["ガン"], kun: ["かお"], meaning: "かお", examples: [{ word: "顔面", reading: "がんめん" }, { word: "笑顔", reading: "えがお" }], strokes: 18 },
  { char: "汽", on: ["キ"], kun: [], meaning: "ゆげ", examples: [{ word: "汽車", reading: "きしゃ" }, { word: "汽笛", reading: "きてき" }], strokes: 7 },
  { char: "記", on: ["キ"], kun: ["しる"], meaning: "かきとめる", examples: [{ word: "日記", reading: "にっき" }, { word: "記入", reading: "きにゅう" }], strokes: 10 },
  { char: "帰", on: ["キ"], kun: ["かえ"], meaning: "かえる", examples: [{ word: "帰国", reading: "きこく" }, { word: "帰る", reading: "かえる" }], strokes: 10 },
  { char: "弓", on: ["キュウ"], kun: ["ゆみ"], meaning: "ゆみ", examples: [{ word: "弓道", reading: "きゅうどう" }, { word: "弓", reading: "ゆみ" }], strokes: 3 },
  { char: "牛", on: ["ギュウ"], kun: ["うし"], meaning: "うし", examples: [{ word: "牛乳", reading: "ぎゅうにゅう" }, { word: "牛", reading: "うし" }], strokes: 4 },
  { char: "魚", on: ["ギョ"], kun: ["さかな", "うお"], meaning: "さかな", examples: [{ word: "金魚", reading: "きんぎょ" }, { word: "魚", reading: "さかな" }], strokes: 11 },
  { char: "京", on: ["キョウ", "ケイ"], kun: [], meaning: "みやこ", examples: [{ word: "東京", reading: "とうきょう" }, { word: "京都", reading: "きょうと" }], strokes: 8 },
  { char: "強", on: ["キョウ", "ゴウ"], kun: ["つよ"], meaning: "つよい", examples: [{ word: "強力", reading: "きょうりょく" }, { word: "強い", reading: "つよい" }], strokes: 11 },
  { char: "教", on: ["キョウ"], kun: ["おし"], meaning: "おしえる", examples: [{ word: "教室", reading: "きょうしつ" }, { word: "教える", reading: "おしえる" }], strokes: 11 },
  { char: "近", on: ["キン"], kun: ["ちか"], meaning: "ちかい", examples: [{ word: "近所", reading: "きんじょ" }, { word: "近い", reading: "ちかい" }], strokes: 7 },
  { char: "兄", on: ["ケイ", "キョウ"], kun: ["あに"], meaning: "おにいさん", examples: [{ word: "兄弟", reading: "きょうだい" }, { word: "兄", reading: "あに" }], strokes: 5 },
  { char: "形", on: ["ケイ", "ギョウ"], kun: ["かたち"], meaning: "かたち", examples: [{ word: "図形", reading: "ずけい" }, { word: "形", reading: "かたち" }], strokes: 7 },
  { char: "計", on: ["ケイ"], kun: ["はか"], meaning: "はかる・かぞえる", examples: [{ word: "計算", reading: "けいさん" }, { word: "計る", reading: "はかる" }], strokes: 9 },
  { char: "元", on: ["ゲン", "ガン"], kun: ["もと"], meaning: "もと・はじめ", examples: [{ word: "元気", reading: "げんき" }, { word: "元日", reading: "がんじつ" }], strokes: 4 },
  { char: "言", on: ["ゲン", "ゴン"], kun: ["い", "こと"], meaning: "ことば・いう", examples: [{ word: "言語", reading: "げんご" }, { word: "言う", reading: "いう" }], strokes: 7 },
  { char: "原", on: ["ゲン"], kun: ["はら"], meaning: "はら・のはら", examples: [{ word: "原野", reading: "げんや" }, { word: "野原", reading: "のはら" }], strokes: 10 },
  { char: "戸", on: ["コ"], kun: ["と"], meaning: "と・とびら", examples: [{ word: "戸外", reading: "こがい" }, { word: "雨戸", reading: "あまど" }], strokes: 4 },
  { char: "古", on: ["コ"], kun: ["ふる"], meaning: "ふるい", examples: [{ word: "古代", reading: "こだい" }, { word: "古い", reading: "ふるい" }], strokes: 5 },
  { char: "午", on: ["ゴ"], kun: [], meaning: "ひる", examples: [{ word: "午前", reading: "ごぜん" }, { word: "正午", reading: "しょうご" }], strokes: 4 },
  { char: "後", on: ["ゴ", "コウ"], kun: ["のち", "うし", "あと"], meaning: "あと・うしろ", examples: [{ word: "午後", reading: "ごご" }, { word: "後ろ", reading: "うしろ" }], strokes: 9 },
  { char: "語", on: ["ゴ"], kun: ["かた"], meaning: "ことば・はなす", examples: [{ word: "国語", reading: "こくご" }, { word: "語る", reading: "かたる" }], strokes: 14 },
  { char: "工", on: ["コウ", "ク"], kun: [], meaning: "つくる", examples: [{ word: "工場", reading: "こうじょう" }, { word: "工作", reading: "こうさく" }], strokes: 3 },
  { char: "公", on: ["コウ"], kun: [], meaning: "おおやけ", examples: [{ word: "公園", reading: "こうえん" }, { word: "公平", reading: "こうへい" }], strokes: 4 },
  { char: "広", on: ["コウ"], kun: ["ひろ"], meaning: "ひろい", examples: [{ word: "広大", reading: "こうだい" }, { word: "広い", reading: "ひろい" }], strokes: 5 },
  { char: "交", on: ["コウ"], kun: ["まじ"], meaning: "まじわる", examples: [{ word: "交通", reading: "こうつう" }, { word: "交じる", reading: "まじる" }], strokes: 6 },
  { char: "光", on: ["コウ"], kun: ["ひか", "ひかり"], meaning: "ひかる・ひかり", examples: [{ word: "光線", reading: "こうせん" }, { word: "光る", reading: "ひかる" }], strokes: 6 },
  { char: "考", on: ["コウ"], kun: ["かんが"], meaning: "かんがえる", examples: [{ word: "考案", reading: "こうあん" }, { word: "考える", reading: "かんがえる" }], strokes: 6 },
  { char: "行", on: ["コウ", "ギョウ"], kun: ["い", "ゆ", "おこな"], meaning: "いく・おこなう", examples: [{ word: "旅行", reading: "りょこう" }, { word: "行く", reading: "いく" }], strokes: 6 },
  { char: "高", on: ["コウ"], kun: ["たか"], meaning: "たかい", examples: [{ word: "高校", reading: "こうこう" }, { word: "高い", reading: "たかい" }], strokes: 10 },
  { char: "黄", on: ["コウ", "オウ"], kun: ["き"], meaning: "きいろ", examples: [{ word: "黄色", reading: "きいろ" }, { word: "黄金", reading: "おうごん" }], strokes: 11 },
  { char: "合", on: ["ゴウ", "ガッ", "カッ"], kun: ["あ"], meaning: "あう・あわせる", examples: [{ word: "合計", reading: "ごうけい" }, { word: "合う", reading: "あう" }], strokes: 6 },
  { char: "谷", on: ["コク"], kun: ["たに"], meaning: "たに", examples: [{ word: "谷川", reading: "たにがわ" }, { word: "谷", reading: "たに" }], strokes: 7 },
  { char: "国", on: ["コク"], kun: ["くに"], meaning: "くに", examples: [{ word: "国語", reading: "こくご" }, { word: "国", reading: "くに" }], strokes: 8 },
  { char: "黒", on: ["コク"], kun: ["くろ"], meaning: "くろ・くろい", examples: [{ word: "黒板", reading: "こくばん" }, { word: "黒い", reading: "くろい" }], strokes: 11 },
  { char: "今", on: ["コン", "キン"], kun: ["いま"], meaning: "いま", examples: [{ word: "今日", reading: "きょう" }, { word: "今", reading: "いま" }], strokes: 4 },
  { char: "才", on: ["サイ"], kun: [], meaning: "とし・ちのう", examples: [{ word: "天才", reading: "てんさい" }, { word: "八才", reading: "はっさい" }], strokes: 3 },
  { char: "細", on: ["サイ"], kun: ["こま", "ほそ"], meaning: "こまかい・ほそい", examples: [{ word: "細工", reading: "さいく" }, { word: "細い", reading: "ほそい" }], strokes: 11 },
  { char: "作", on: ["サク", "サ"], kun: ["つく"], meaning: "つくる", examples: [{ word: "作品", reading: "さくひん" }, { word: "作る", reading: "つくる" }], strokes: 7 },
  { char: "算", on: ["サン"], kun: [], meaning: "けいさんする", examples: [{ word: "算数", reading: "さんすう" }, { word: "計算", reading: "けいさん" }], strokes: 14 },
  { char: "止", on: ["シ"], kun: ["と"], meaning: "とまる・とめる", examples: [{ word: "中止", reading: "ちゅうし" }, { word: "止まる", reading: "とまる" }], strokes: 4 },
  { char: "市", on: ["シ"], kun: ["いち"], meaning: "まち・いちば", examples: [{ word: "市内", reading: "しない" }, { word: "市場", reading: "いちば" }], strokes: 5 },
  { char: "矢", on: ["シ"], kun: ["や"], meaning: "や", examples: [{ word: "矢印", reading: "やじるし" }, { word: "矢", reading: "や" }], strokes: 5 },
  { char: "姉", on: ["シ"], kun: ["あね"], meaning: "おねえさん", examples: [{ word: "姉妹", reading: "しまい" }, { word: "姉", reading: "あね" }], strokes: 8 },
  { char: "思", on: ["シ"], kun: ["おも"], meaning: "おもう", examples: [{ word: "思考", reading: "しこう" }, { word: "思う", reading: "おもう" }], strokes: 9 },
  { char: "紙", on: ["シ"], kun: ["かみ"], meaning: "かみ", examples: [{ word: "用紙", reading: "ようし" }, { word: "紙", reading: "かみ" }], strokes: 10 },
  { char: "寺", on: ["ジ"], kun: ["てら"], meaning: "おてら", examples: [{ word: "寺院", reading: "じいん" }, { word: "寺", reading: "てら" }], strokes: 6 },
  { char: "自", on: ["ジ", "シ"], kun: ["みずか"], meaning: "じぶん", examples: [{ word: "自分", reading: "じぶん" }, { word: "自由", reading: "じゆう" }], strokes: 6 },
  { char: "時", on: ["ジ"], kun: ["とき"], meaning: "とき・じかん", examples: [{ word: "時計", reading: "とけい" }, { word: "時", reading: "とき" }], strokes: 10 },
  { char: "室", on: ["シツ"], kun: ["むろ"], meaning: "へや", examples: [{ word: "教室", reading: "きょうしつ" }, { word: "室内", reading: "しつない" }], strokes: 9 },
  { char: "社", on: ["シャ"], kun: ["やしろ"], meaning: "やしろ・かいしゃ", examples: [{ word: "会社", reading: "かいしゃ" }, { word: "神社", reading: "じんじゃ" }], strokes: 7 },
  { char: "弱", on: ["ジャク"], kun: ["よわ"], meaning: "よわい", examples: [{ word: "弱点", reading: "じゃくてん" }, { word: "弱い", reading: "よわい" }], strokes: 10 },
  { char: "首", on: ["シュ"], kun: ["くび"], meaning: "くび", examples: [{ word: "首都", reading: "しゅと" }, { word: "首", reading: "くび" }], strokes: 9 },
  { char: "秋", on: ["シュウ"], kun: ["あき"], meaning: "あき", examples: [{ word: "秋分", reading: "しゅうぶん" }, { word: "秋", reading: "あき" }], strokes: 9 },
  { char: "週", on: ["シュウ"], kun: [], meaning: "なのか", examples: [{ word: "今週", reading: "こんしゅう" }, { word: "週末", reading: "しゅうまつ" }], strokes: 11 },
  { char: "春", on: ["シュン"], kun: ["はる"], meaning: "はる", examples: [{ word: "春分", reading: "しゅんぶん" }, { word: "春", reading: "はる" }], strokes: 9 },
  { char: "書", on: ["ショ"], kun: ["か"], meaning: "かく", examples: [{ word: "書道", reading: "しょどう" }, { word: "書く", reading: "かく" }], strokes: 10 },
  { char: "少", on: ["ショウ"], kun: ["すく", "すこ"], meaning: "すこし", examples: [{ word: "少年", reading: "しょうねん" }, { word: "少し", reading: "すこし" }], strokes: 4 },
  { char: "場", on: ["ジョウ"], kun: ["ば"], meaning: "ばしょ", examples: [{ word: "工場", reading: "こうじょう" }, { word: "場所", reading: "ばしょ" }], strokes: 12 },
  { char: "色", on: ["ショク", "シキ"], kun: ["いろ"], meaning: "いろ", examples: [{ word: "色紙", reading: "いろがみ" }, { word: "三色", reading: "さんしょく" }], strokes: 6 },
  { char: "食", on: ["ショク", "ジキ"], kun: ["た", "く"], meaning: "たべる", examples: [{ word: "食事", reading: "しょくじ" }, { word: "食べる", reading: "たべる" }], strokes: 9 },
  { char: "心", on: ["シン"], kun: ["こころ"], meaning: "こころ", examples: [{ word: "心配", reading: "しんぱい" }, { word: "心", reading: "こころ" }], strokes: 4 },
  { char: "新", on: ["シン"], kun: ["あたら"], meaning: "あたらしい", examples: [{ word: "新聞", reading: "しんぶん" }, { word: "新しい", reading: "あたらしい" }], strokes: 13 },
  { char: "親", on: ["シン"], kun: ["おや", "した"], meaning: "おや・したしい", examples: [{ word: "親友", reading: "しんゆう" }, { word: "親", reading: "おや" }], strokes: 16 },
  { char: "図", on: ["ズ", "ト"], kun: ["はか"], meaning: "ず・え", examples: [{ word: "地図", reading: "ちず" }, { word: "図書", reading: "としょ" }], strokes: 7 },
  { char: "数", on: ["スウ"], kun: ["かず", "かぞ"], meaning: "かず・かぞえる", examples: [{ word: "数学", reading: "すうがく" }, { word: "数える", reading: "かぞえる" }], strokes: 13 },
  { char: "西", on: ["セイ", "サイ"], kun: ["にし"], meaning: "にし", examples: [{ word: "西日", reading: "にしび" }, { word: "西洋", reading: "せいよう" }], strokes: 6 },
  { char: "声", on: ["セイ", "ショウ"], kun: ["こえ"], meaning: "こえ", examples: [{ word: "音声", reading: "おんせい" }, { word: "声", reading: "こえ" }], strokes: 7 },
  { char: "星", on: ["セイ", "ショウ"], kun: ["ほし"], meaning: "ほし", examples: [{ word: "星空", reading: "ほしぞら" }, { word: "火星", reading: "かせい" }], strokes: 9 },
  { char: "晴", on: ["セイ"], kun: ["は"], meaning: "はれる", examples: [{ word: "晴天", reading: "せいてん" }, { word: "晴れ", reading: "はれ" }], strokes: 12 },
  { char: "切", on: ["セツ", "サイ"], kun: ["き"], meaning: "きる", examples: [{ word: "親切", reading: "しんせつ" }, { word: "切る", reading: "きる" }], strokes: 4 },
  { char: "雪", on: ["セツ"], kun: ["ゆき"], meaning: "ゆき", examples: [{ word: "大雪", reading: "おおゆき" }, { word: "雪", reading: "ゆき" }], strokes: 11 },
  { char: "船", on: ["セン"], kun: ["ふね"], meaning: "ふね", examples: [{ word: "船長", reading: "せんちょう" }, { word: "船", reading: "ふね" }], strokes: 11 },
  { char: "線", on: ["セン"], kun: [], meaning: "せん", examples: [{ word: "直線", reading: "ちょくせん" }, { word: "線", reading: "せん" }], strokes: 15 },
  { char: "前", on: ["ゼン"], kun: ["まえ"], meaning: "まえ", examples: [{ word: "午前", reading: "ごぜん" }, { word: "前", reading: "まえ" }], strokes: 9 },
  { char: "組", on: ["ソ"], kun: ["く", "くみ"], meaning: "くみ・くむ", examples: [{ word: "組合", reading: "くみあい" }, { word: "番組", reading: "ばんぐみ" }], strokes: 11 },
  { char: "走", on: ["ソウ"], kun: ["はし"], meaning: "はしる", examples: [{ word: "走者", reading: "そうしゃ" }, { word: "走る", reading: "はしる" }], strokes: 7 },
  { char: "多", on: ["タ"], kun: ["おお"], meaning: "おおい", examples: [{ word: "多数", reading: "たすう" }, { word: "多い", reading: "おおい" }], strokes: 6 },
  { char: "太", on: ["タイ", "タ"], kun: ["ふと"], meaning: "ふとい", examples: [{ word: "太陽", reading: "たいよう" }, { word: "太い", reading: "ふとい" }], strokes: 4 },
  { char: "体", on: ["タイ"], kun: ["からだ"], meaning: "からだ", examples: [{ word: "体育", reading: "たいいく" }, { word: "体", reading: "からだ" }], strokes: 7 },
  { char: "台", on: ["ダイ", "タイ"], kun: [], meaning: "だい・うてな", examples: [{ word: "台所", reading: "だいどころ" }, { word: "一台", reading: "いちだい" }], strokes: 5 },
  { char: "地", on: ["チ", "ジ"], kun: [], meaning: "つち・ばしょ", examples: [{ word: "地図", reading: "ちず" }, { word: "地面", reading: "じめん" }], strokes: 6 },
  { char: "池", on: ["チ"], kun: ["いけ"], meaning: "いけ", examples: [{ word: "電池", reading: "でんち" }, { word: "池", reading: "いけ" }], strokes: 6 },
  { char: "知", on: ["チ"], kun: ["し"], meaning: "しる", examples: [{ word: "知人", reading: "ちじん" }, { word: "知る", reading: "しる" }], strokes: 8 },
  { char: "茶", on: ["チャ", "サ"], kun: [], meaning: "おちゃ", examples: [{ word: "茶色", reading: "ちゃいろ" }, { word: "緑茶", reading: "りょくちゃ" }], strokes: 9 },
  { char: "昼", on: ["チュウ"], kun: ["ひる"], meaning: "ひる", examples: [{ word: "昼食", reading: "ちゅうしょく" }, { word: "昼", reading: "ひる" }], strokes: 9 },
  { char: "長", on: ["チョウ"], kun: ["なが"], meaning: "ながい", examples: [{ word: "校長", reading: "こうちょう" }, { word: "長い", reading: "ながい" }], strokes: 8 },
  { char: "鳥", on: ["チョウ"], kun: ["とり"], meaning: "とり", examples: [{ word: "白鳥", reading: "はくちょう" }, { word: "鳥", reading: "とり" }], strokes: 11 },
  { char: "朝", on: ["チョウ"], kun: ["あさ"], meaning: "あさ", examples: [{ word: "朝食", reading: "ちょうしょく" }, { word: "朝", reading: "あさ" }], strokes: 12 },
  { char: "直", on: ["チョク", "ジキ"], kun: ["なお"], meaning: "まっすぐ・なおす", examples: [{ word: "直線", reading: "ちょくせん" }, { word: "直す", reading: "なおす" }], strokes: 8 },
  { char: "通", on: ["ツウ"], kun: ["とお", "かよ"], meaning: "とおる・かよう", examples: [{ word: "通学", reading: "つうがく" }, { word: "通る", reading: "とおる" }], strokes: 10 },
  { char: "弟", on: ["テイ", "ダイ"], kun: ["おとうと"], meaning: "おとうと", examples: [{ word: "兄弟", reading: "きょうだい" }, { word: "弟", reading: "おとうと" }], strokes: 7 },
  { char: "店", on: ["テン"], kun: ["みせ"], meaning: "みせ", examples: [{ word: "書店", reading: "しょてん" }, { word: "店", reading: "みせ" }], strokes: 8 },
  { char: "点", on: ["テン"], kun: [], meaning: "てん", examples: [{ word: "点数", reading: "てんすう" }, { word: "100点", reading: "ひゃくてん" }], strokes: 9 },
  { char: "電", on: ["デン"], kun: [], meaning: "でんき", examples: [{ word: "電車", reading: "でんしゃ" }, { word: "電気", reading: "でんき" }], strokes: 13 },
  { char: "刀", on: ["トウ"], kun: ["かたな"], meaning: "かたな", examples: [{ word: "日本刀", reading: "にほんとう" }, { word: "刀", reading: "かたな" }], strokes: 2 },
  { char: "冬", on: ["トウ"], kun: ["ふゆ"], meaning: "ふゆ", examples: [{ word: "冬季", reading: "とうき" }, { word: "冬", reading: "ふゆ" }], strokes: 5 },
  { char: "当", on: ["トウ"], kun: ["あ"], meaning: "あたる", examples: [{ word: "本当", reading: "ほんとう" }, { word: "当たる", reading: "あたる" }], strokes: 6 },
  { char: "東", on: ["トウ"], kun: ["ひがし"], meaning: "ひがし", examples: [{ word: "東京", reading: "とうきょう" }, { word: "東", reading: "ひがし" }], strokes: 8 },
  { char: "答", on: ["トウ"], kun: ["こた"], meaning: "こたえる", examples: [{ word: "答案", reading: "とうあん" }, { word: "答え", reading: "こたえ" }], strokes: 12 },
  { char: "頭", on: ["トウ", "ズ"], kun: ["あたま"], meaning: "あたま", examples: [{ word: "頭脳", reading: "ずのう" }, { word: "頭", reading: "あたま" }], strokes: 16 },
  { char: "同", on: ["ドウ"], kun: ["おな"], meaning: "おなじ", examples: [{ word: "同時", reading: "どうじ" }, { word: "同じ", reading: "おなじ" }], strokes: 6 },
  { char: "道", on: ["ドウ", "トウ"], kun: ["みち"], meaning: "みち", examples: [{ word: "道路", reading: "どうろ" }, { word: "道", reading: "みち" }], strokes: 12 },
  { char: "読", on: ["ドク", "トク"], kun: ["よ"], meaning: "よむ", examples: [{ word: "読書", reading: "どくしょ" }, { word: "読む", reading: "よむ" }], strokes: 14 },
  { char: "内", on: ["ナイ", "ダイ"], kun: ["うち"], meaning: "なか・うち", examples: [{ word: "国内", reading: "こくない" }, { word: "内側", reading: "うちがわ" }], strokes: 4 },
  { char: "南", on: ["ナン"], kun: ["みなみ"], meaning: "みなみ", examples: [{ word: "南北", reading: "なんぼく" }, { word: "南", reading: "みなみ" }], strokes: 9 },
  { char: "肉", on: ["ニク"], kun: [], meaning: "にく", examples: [{ word: "牛肉", reading: "ぎゅうにく" }, { word: "肉", reading: "にく" }], strokes: 6 },
  { char: "馬", on: ["バ"], kun: ["うま"], meaning: "うま", examples: [{ word: "馬車", reading: "ばしゃ" }, { word: "馬", reading: "うま" }], strokes: 10 },
  { char: "売", on: ["バイ"], kun: ["う"], meaning: "うる", examples: [{ word: "売店", reading: "ばいてん" }, { word: "売る", reading: "うる" }], strokes: 7 },
  { char: "買", on: ["バイ"], kun: ["か"], meaning: "かう", examples: [{ word: "買い物", reading: "かいもの" }, { word: "買う", reading: "かう" }], strokes: 12 },
  { char: "麦", on: ["バク"], kun: ["むぎ"], meaning: "むぎ", examples: [{ word: "麦茶", reading: "むぎちゃ" }, { word: "麦", reading: "むぎ" }], strokes: 7 },
  { char: "半", on: ["ハン"], kun: ["なか"], meaning: "はんぶん", examples: [{ word: "半分", reading: "はんぶん" }, { word: "半年", reading: "はんとし" }], strokes: 5 },
  { char: "番", on: ["バン"], kun: [], meaning: "じゅんばん", examples: [{ word: "番号", reading: "ばんごう" }, { word: "一番", reading: "いちばん" }], strokes: 12 },
  { char: "父", on: ["フ"], kun: ["ちち"], meaning: "おとうさん", examples: [{ word: "父母", reading: "ふぼ" }, { word: "父", reading: "ちち" }], strokes: 4 },
  { char: "風", on: ["フウ", "フ"], kun: ["かぜ"], meaning: "かぜ", examples: [{ word: "風船", reading: "ふうせん" }, { word: "風", reading: "かぜ" }], strokes: 9 },
  { char: "分", on: ["ブン", "フン", "ブ"], kun: ["わ"], meaning: "わける・ふん", examples: [{ word: "三分", reading: "さんぷん" }, { word: "分ける", reading: "わける" }], strokes: 4 },
  { char: "聞", on: ["ブン", "モン"], kun: ["き"], meaning: "きく", examples: [{ word: "新聞", reading: "しんぶん" }, { word: "聞く", reading: "きく" }], strokes: 14 },
  { char: "米", on: ["ベイ", "マイ"], kun: ["こめ"], meaning: "こめ", examples: [{ word: "米国", reading: "べいこく" }, { word: "米", reading: "こめ" }], strokes: 6 },
  { char: "歩", on: ["ホ", "ブ"], kun: ["ある"], meaning: "あるく", examples: [{ word: "散歩", reading: "さんぽ" }, { word: "歩く", reading: "あるく" }], strokes: 8 },
  { char: "母", on: ["ボ"], kun: ["はは"], meaning: "おかあさん", examples: [{ word: "母校", reading: "ぼこう" }, { word: "母", reading: "はは" }], strokes: 5 },
  { char: "方", on: ["ホウ"], kun: ["かた"], meaning: "ほうこう・かた", examples: [{ word: "方法", reading: "ほうほう" }, { word: "夕方", reading: "ゆうがた" }], strokes: 4 },
  { char: "北", on: ["ホク"], kun: ["きた"], meaning: "きた", examples: [{ word: "北海道", reading: "ほっかいどう" }, { word: "北", reading: "きた" }], strokes: 5 },
  { char: "毎", on: ["マイ"], kun: [], meaning: "いつも・まいかい", examples: [{ word: "毎日", reading: "まいにち" }, { word: "毎週", reading: "まいしゅう" }], strokes: 6 },
  { char: "妹", on: ["マイ"], kun: ["いもうと"], meaning: "いもうと", examples: [{ word: "姉妹", reading: "しまい" }, { word: "妹", reading: "いもうと" }], strokes: 8 },
  { char: "万", on: ["マン", "バン"], kun: [], meaning: "まん（10000）", examples: [{ word: "一万", reading: "いちまん" }, { word: "万年", reading: "まんねん" }], strokes: 3 },
  { char: "明", on: ["メイ", "ミョウ"], kun: ["あか"], meaning: "あかるい", examples: [{ word: "明日", reading: "あした" }, { word: "明るい", reading: "あかるい" }], strokes: 8 },
  { char: "鳴", on: ["メイ"], kun: ["な"], meaning: "なく・なる", examples: [{ word: "鳴動", reading: "めいどう" }, { word: "鳴く", reading: "なく" }], strokes: 14 },
  { char: "毛", on: ["モウ"], kun: ["け"], meaning: "け", examples: [{ word: "毛糸", reading: "けいと" }, { word: "毛皮", reading: "けがわ" }], strokes: 4 },
  { char: "門", on: ["モン"], kun: ["かど"], meaning: "もん", examples: [{ word: "校門", reading: "こうもん" }, { word: "門", reading: "もん" }], strokes: 8 },
  { char: "夜", on: ["ヤ"], kun: ["よる", "よ"], meaning: "よる", examples: [{ word: "夜空", reading: "よぞら" }, { word: "夜", reading: "よる" }], strokes: 8 },
  { char: "野", on: ["ヤ"], kun: ["の"], meaning: "のはら", examples: [{ word: "野球", reading: "やきゅう" }, { word: "野原", reading: "のはら" }], strokes: 11 },
  { char: "友", on: ["ユウ"], kun: ["とも"], meaning: "ともだち", examples: [{ word: "友人", reading: "ゆうじん" }, { word: "友達", reading: "ともだち" }], strokes: 4 },
  { char: "用", on: ["ヨウ"], kun: ["もち"], meaning: "つかう", examples: [{ word: "用事", reading: "ようじ" }, { word: "用いる", reading: "もちいる" }], strokes: 5 },
  { char: "曜", on: ["ヨウ"], kun: [], meaning: "ようび", examples: [{ word: "月曜", reading: "げつよう" }, { word: "曜日", reading: "ようび" }], strokes: 18 },
  { char: "来", on: ["ライ"], kun: ["く"], meaning: "くる", examples: [{ word: "来年", reading: "らいねん" }, { word: "来る", reading: "くる" }], strokes: 7 },
  { char: "里", on: ["リ"], kun: ["さと"], meaning: "むら・さと", examples: [{ word: "里山", reading: "さとやま" }, { word: "千里", reading: "せんり" }], strokes: 7 },
  { char: "理", on: ["リ"], kun: [], meaning: "ことわり・わけ", examples: [{ word: "理科", reading: "りか" }, { word: "理由", reading: "りゆう" }], strokes: 11 },
  { char: "話", on: ["ワ"], kun: ["はな", "はなし"], meaning: "はなす・はなし", examples: [{ word: "電話", reading: "でんわ" }, { word: "話す", reading: "はなす" }], strokes: 13 }
];

